//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theatre
    {
        public int TId { get; set; }
        public string Tname { get; set; }
        public string Tlocation { get; set; }
        public int MovieMId { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
